environment: production
version: 1.0.0

logging:
  level: INFO
  appenders:
    - type: console

server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081